---
title: "severité"
output: html_document
date: "2025-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importation des données

```{r}
df = read.csv("../data/ONISR-2021.csv")
head(df)
#head(class(df$nb_hospitalise))
```

```{r}
non_numeric = colnames(df)[(sapply(df, class) != "integer")*(sapply(df, class) != "numeric") == 1]
#non_numeric
```

```{r}
cat("Variables avec >= différentes valeurs\n")
for (i in non_numeric){
  if (length(table(df[i])) >= 20){
    print(i)
  }
}

cat("\nVariables avec < différentes valeurs\n")
for (i in non_numeric){
  if (length(table(df[i])) < 20){
    print(i)
  }
}
```

```{r}
library(dplyr)

# Remplacer les textes par des nombres
df$lum <- recode(df$lum,
                   "plein jour" = 1,
                   "crepuscule ou aube" = 2,
                   "nuit sans eclairage" = 3,
                  "nuit avec eclairage non allume" = 4,
                   "nuit avec eclairage allume" = 5)
```


```{r}
```


```{r}
df$agg <- recode(df$agg,
                   "hors agglo" = 1,
                   "en agglo" = 2)

df$int <- recode(df$int,
                   "aucune" = 1,
                   "en X" = 2,
                   "en T" = 3,
                   "en Y" = 4,
                   "4+ branches" = 5,
                   "giratoire" = 6,
                   "place" = 7,
                   "passage a niveau" = 8,
                   "autre" = 9)

df$atm <- recode(df$atm,
                   .missing = -1,
                   "normale" = 1,
                   "pluie legere" = 2,
                   "pluie forte" = 3,
                   "neige ou grele" = 4,
                   "brouillard ou fumee" = 5,
                   "vent fort ou tempete" = 6,
                   "eblouissant" = 7,
                   "couvert" = 8,
                   "autre" = 9
                   )

df$col <- recode(df$col,
                   .missing = -1,
                   "deux veh - frontal" = 1,
                   "deux veh - arriere" = 2,
                   "deux veh - cote" = 3,
                   "3+ veh - en chaine" = 4,
                   "3+ veh - multiple" = 5,
                   "autre"  = 6,
                   "sans" = 7)

df$catr <- recode(df$catr,
                    "autoroute" = 1,
                    "nationale" = 2,
                    "departementale" = 3,
                    "communale" = 4,
                    "hors reseau" = 5,
                    "parc" = 6,
                    "metropole" = 7,
                    "autre" = 9)

df$circ <- recode(df$circ,
                    .missing = -1,
                    "sens unique" = 1,
                    "bidirectionnel" = 2,
                    "chaussee separees" = 3,
                    "avec voies d'affectation variable" = 4)

df$vosp <- recode(df$vosp,
                    .missing = -1,
                    "sans objet" = 0,
                    "piste cyclable" = 1,
                    "bande cyclable" = 2,
                    "voie reservee" = 3)

df$prof <- recode(df$prof,
                    .missing = -1,
                    "plat" = 1,
                    "pente" = 2,
                    "sommet de cote" = 3,
                    "base de cote" = 4)

df$plan <- recode(df$plan,
                    .mising = -1,
                    "rectiligne"  = 1,
                    "en courbe a gauche" = 2,
                    "en courbe a droite" = 3,
                    "en S" = 4)

df$surf <- recode(df$surf,
                    .missing = -1,
                    "normale" = 1,
                    "mouillee" = 2,
                    "flaques" = 3,
                    "inondee" = 4,
                    "enneigee" = 5,
                    "boue" = 6,
                    "verglacee" = 7,
                    "corps gras" = 8,
                    "autre" = 9)

df$infra <- recode(df$infra,
                     .missing = -1,
                     "aucun" = 0,
                     "souterrain ou tunnel" = 1,
                     "pont ou autopont" = 2,
                     "bretelle ou échangeur" = 3,
                     "voie ferree" = 4,
                     "carrefour" = 5,
                     "zone pietonne" = 6,
                     "peage"= 7,
                     "chantier" = 8,
                     "autres" = 9)

df$situ <- recode(df$situ,
                    .missing = -1,
                    "aucun" = 0,
                    "chaussee" = 1,
                    "bande arret urgence" = 2,
                    "accotement" = 3,
                    "trottoir" = 4,
                    "piste cyclable" = 5,
                    "voie speciale" = 6,
                    "autres" = 8)
```

```{r}
df$Score_de_severite <- (1 * df$nb_blesse) +   (7 * df$nb_hospitalise) +  (16 * df$nb_tue)
# 3. Export et vérification
write.csv(df, "ONISR-2021_avec_severite.csv", row.names = FALSE)
head(df[, c("nb_indemne", "nb_blesse", "nb_hospitalise", "nb_tue", "Score_de_severite")])
```

```{r}
```


```{r}
df[50:150, ]
```

```{r}
```

```{r}
# 1. Matrice de corrélation (Uniquement variables numériques)
library(corrplot)
#df_resultat = df[,c("Num_Acc","nb_tue","nb_hospitalise","nb_blesse","nb_indemne","Score_de_severite")]
#resultat = df[,setdiff(colnames(df),c("Num_Acc","nb_tue","nb_hospitalise","nb_blesse","nb_indemne","Score_de_severite"))]
#modele = lm(df_resultat$Score_de_severite~resultat$col)
#resume = summary(modele)
#resume 
```

```{r}
#modele = lm(df_resultat$Score_de_severite~resultat$col+resultat$catr+resultat$atm+resultat$int+resultat$agg+resultat$situ)
#resume = summary(modele)
#resume
```
```{r}
# On s'assure que la VMA est bien numérique (c'est une grandeur physique)
df$vma <- as.numeric(as.character(df$vma))

# On construit le modèle en précisant 'factor()' pour les variables recodées
# Cela dit à R : "Ne traite pas 1,2,3 comme des nombres, mais comme des groupes distincts"
modele_optimise <- lm(Score_de_severite ~ 
                        factor(vma) +                # Grandeur physique (Linearité OK)
                        factor(col) +        # Type de choc (Vital)
                        factor(agg) +        # Localisation (Vital)
                        factor(catr) +       # Type de route
                        factor(lum),         # Luminosité (Nuit sans éclairage impacte)
                      data = df)



summary(modele_optimise)
```
```{r}




```

