```{r}
df <- read.csv("ONISR-2021.csv")
head(df)
```

```{r}
str(df)
```

```{r}
#librairies pour Pipe (%>%) et manipuler des strings
if(!require(dplyr)) install.packages("dplyr")
if(!require(stringr)) install.packages("stringr")
library(dplyr)
library(stringr)
```

```{r}
# Création d'une fonction pour regrouper les départements par régions

get_region <- function(dep_code) {
  # On s'assure que l'entrée est un chr
  d <- as.character(dep_code)
  
  case_when(
    # Gestion de la Corse (2A et 2B)
    d %in% c("2A", "2B", "20") ~ "Corse",
    
    # Gestion des DOM (codes commençant par 97)
    substr(d, 1, 2) == "97" ~ "Outre-Mer",
    
    # Départements standards (on gère les cas "1" et "01")
    # Auvergne-Rhône-Alpes
    d %in% c("01", "1", "03", "3", "07", "7", "15", "26", "38", "42", "43", "63", "69", "73", "74") ~ "Auvergne-Rhône-Alpes",
    
    # Hauts-de-France
    d %in% c("02", "2", "59", "60", "62", "80") ~ "Hauts-de-France",
    
    # PACA
    d %in% c("04", "4", "05", "5", "06", "6", "13", "83", "84") ~ "PACA",
    
    # Grand Est
    d %in% c("08", "8", "10", "51", "52", "54", "55", "57", "67", "68", "88") ~ "Grand Est",
    
    # Occitanie
    d %in% c("09", "9", "11", "12", "30", "31", "32", "34", "46", "48", "65", "66", "81", "82") ~ "Occitanie",
    
    # Normandie
    d %in% c("14", "27", "50", "61", "76") ~ "Normandie",
    
    # Nouvelle-Aquitaine
    d %in% c("16", "17", "19", "23", "24", "33", "40", "47", "64", "79", "86", "87") ~ "Nouvelle-Aquitaine",
    
    # Centre-Val de Loire
    d %in% c("18", "28", "36", "37", "41", "45") ~ "Centre-Val de Loire",
    
    # Bourgogne-Franche-Comté
    d %in% c("21", "25", "39", "58", "70", "71", "89", "90") ~ "Bourgogne-Franche-Comté",
    
    # Bretagne
    d %in% c("22", "29", "35", "56") ~ "Bretagne",
    
    # Pays de la Loire
    d %in% c("44", "49", "53", "72", "85") ~ "Pays de la Loire",
    
    # Île-de-France
    d %in% c("75", "77", "78", "91", "92", "93", "94", "95") ~ "Île-de-France"
  )
}
```

```{r}
# Coefficients pour le calcul du score de sévérité
a <- 10
b <- 5
c <- 1

df_final <- df %>%
 
  # On ajoute la colonne du score de sévérité 
  mutate(
    Score_Severite = (nb_tue * a) + (nb_hospitalise * b) + (nb_blesse *c)
)%>%
  
  # On transforme l'heure en un numeric compris entre 0 et 23
  # en extrayant la première partie de hrmn (heure:min)
  mutate(
    Heure_Num= as.numeric(str_sub(hrmn, 1, 2))
  ) %>%
  
  # On crée une variable Moment pour séparer les moments de la journée
  mutate(
    Moment = case_when(
      Heure_Num >= 0 & Heure_Num <= 5  ~ "Nuit Profonde",
      Heure_Num >= 6 & Heure_Num <= 10 ~ "Matin (Pointe)",
      Heure_Num >= 11 & Heure_Num <= 16 ~ "Journee (Creuse)",
      Heure_Num >= 17 & Heure_Num <= 21 ~ "Soir (Pointe)",
      Heure_Num >= 22 & Heure_Num <= 23 ~ "Soiree",
      TRUE ~ "Autre" # Sécurité
    ),
    # On transforme en factor et on choisit "Journée" comme référence
    Moment = factor(Moment, levels = c("Journée (Creuse)", "Matin (Pointe)", "Soir (Pointe)", "Soirée", "Nuit Profonde")))%>%
  
  # On crée la colonne région
  mutate(
    Region = get_region(dep),
    Region = as.factor(Region)
  ) %>%
  
  # On garde que les variables intéressantes i.e
  # en enlevant les identifiants (Num_Acc, adr), les variables quasi vides (pr, lartpc..), ou avec trop de catégories (com, dep)
  select(
    Score_Severite,
    Region,
    Moment,
    lum, agg, int, atm, col, 
    catr, circ, prof, plan, surf, infra, situ, 
    vma, 
    nb_velo, nb_moto, nb_voiture, nb_utilitaire, nb_camion, nb_transport
  ) %>%
  
    
  # On convertit les variables chr en factor pour que r les traitent comme des variables qualitatives
  mutate_if(is.character, as.factor) %>%
  
  # On supprime les lignes avec des valeurs manquantes
  na.omit
```

```{r}
str(df_final)
```

Après ce nettoyage, on a perdu seulement environ 4 000 lignes, ce qui est négligeable puisqu'il nous reste 52 000 lignes et nous avons gagné en qualité.

```{r}
# R crée des levels pour les variables factor afin de comparer ces levels par rapport à un level de référence (Intercept).
# Mais initialement R choisit le level de référence par ordre alphabétique, ce qui n'est pas forcément souhaitable 
```

```{r}
# Par exemple, R a choisit la référence "aube ou crépuscule" alors qu'on voudrait mieux comparer par rapport à la référence "plein jour"
levels(df_final$lum)
```

```{r}
# On affecte le level de référence que l'on souhaite
df_final$lum <- relevel(df_final$lum, ref = "plein jour", silent=TRUE)
df_final$atm <- relevel(df_final$atm, ref = "normale", silent=TRUE)
df_final$prof <- relevel(df_final$prof, ref = "plat", silent=TRUE)
df_final$plan <- relevel(df_final$plan, ref = "rectiligne", silent=TRUE)
df_final$surf <- relevel(df_final$surf, ref = "normale", silent=TRUE)
df_final$int <- relevel(df_final$int, ref = "aucune", silent=TRUE)
df_final$catr <- relevel(df_final$catr, ref = "departementale", silent=TRUE)
df_final$situ <- relevel(df_final$situ, ref = "chaussee", silent=TRUE)
```

```{r}
# Vérifions 
cat("Référence pour LUM :", levels(df_final$lum)[1], "\n")
cat("Référence pour ATM :", levels(df_final$atm)[1], "\n")
cat("Référence pour PROF :", levels(df_final$prof)[1], "\n")
cat("Référence pour PLAN :", levels(df_final$plan)[1], "\n")
cat("Référence pour SURF :", levels(df_final$surf)[1], "\n")
cat("Référence pour INT :", levels(df_final$int)[1], "\n")
cat("Référence pour CATR :", levels(df_final$catr)[1], "\n")
cat("Référence pour SITU :", levels(df_final$situ)[1], "\n")
```

Ainsi, lorsque l'on va calculer la régression, Intercept correspondra au score de sévérité moyen quand tout est à la référence (Plein jour, Météo normale, route plate, etc.)

```{r}
# Modèle de régression: Score de sévérité expliqué par toutes les colonnes
modele <- lm(Score_Severite ~ ., data = df_final)

summary(modele)
```

```{r}
# On divise la fenêtre graphique en 4 (2x2)
par(mfrow = c(2, 2))

# On affiche les 4 graphiques de diagnostic
plot(modele)

# On remet la fenêtre graphique normale
par(mfrow = c(1, 1))
```

```{r}
# Librairie pour le calcul du VIF (Variance Inflation Factor) (cf Cuthbert Daniel)
if(!require(car)) install.packages("car")
library(car)

# Calcul du VIF
vif_values <- vif(modele)

# Affichage clair
print(vif_values)
```

```{r}
# Distribution des résidus
hist(resid(modele), 
     breaks = 50, 
     col = "lightblue", 
     main = "Distribution des Résidus",
     xlab = "Erreur du modèle")
```

\`\`\`
